import type { Metadata } from "next";
import { AntdProvider } from "@/components/providers/AntdProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "PromptForge App",
  description: "Generated by PromptForge",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AntdProvider>{children}</AntdProvider>
      </body>
    </html>
  );
}
